### ISSUE TITLE
HTTP 500 Uploading An EML File

### ISSUE THREAD

**Issue by schrodyn** [swimlane/safe-mail#2]
## Problem

Error uploading an eml file.

```
[2020-04-03 08:27:25,647] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/safemail/app.py", line 111, in handle_upload
    process_uploads(os.path.join(app.config['UPLOAD_FOLDER'], file.filename))
  File "/app/safemail/app.py", line 84, in process_uploads
    converted_file, image = safemail.convert_eml(file_name)
  File "/app/safemail/safemail.py", line 142, in convert_eml
    return_file = eml.process(f.read(), image_name)
  File "/app/safemail/emlrender.py", line 210, in process
    fileName = str(fileName.encode('utf-8')).replace("b'",'', 1).rstrip("'")
AttributeError: 'NoneType' object has no attribute 'encode'
192.168.0.1 - - [03/Apr/2020:08:27:25 +0000] "POST /upload HTTP/1.1" 500 290 "http://0.0.0.0:7001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
```

## Steps to reproduce

* git clone https://github.com/swimlane/safe-mail
* docker build --force-rm -t safe-mail .
* docker run -p 7001:7001 -ti safe-mail
* Uploaded file via webUI

**Comment by joshswimlane** [comment]
Do you mind providing the EML you used? 

Also please try running 

python3 -m pytest
